### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jpechmann** [agrc/ironing-board#106]
The link to "Utah Enterprise Zones Map" off of
http://business.utah.gov/programs/incentives/enterprise-zones/ will not load the map on locate.utah.gov.

**Comment by stdavis** [comment]
Yes, those map extents in the URL are in UTM. They need to open locate.utah.gov and set up the URL again to their liking and update their URL.

**Comment by jpechmann** [comment]
@brigsz, Matt, back to you. Do you know the contact for that part of the GOED website? Or should I just contact Kelleigh Cole?

**Comment by brigsz** [comment]
I would pass it on to the IT Director, I think it is still Amie, she would
know where to route it.
