### ISSUE TITLE
place finding

### ISSUE THREAD

**Issue by stdavis** [agrc/ironing-board#108]
As a user I want an easy way to find cities during my search so I am not lost and don’t need to be familiar with Utah. 

As a user I want some cartographic enhancements to help highlight counties as I look at SureSites so I don’t need to have a good understanding of county names and location. Maybe an overlay of county boundaries to make them stand out more on the lite basemap.

**Comment by stdavis** [comment]
@brigsz: Need to know what the decision is for the second paragraph of this issue. Just overlay county boundaries? Do I duplicate the labels over the top of the base map labels?

**Comment by steveoh** [comment]
overlaying the labels sounds messy. 

Other visual clues:
show somewhere in the UI what county folks are looking at
???

**Comment by brigsz** [comment]
I would be tempted to pass this one over.


The general thought was that the basemaps don't emphasize the individual counties really well.  You see the boundaries if you are looking for them, but they don't pop out and hit you in the eyeballs.  If you have an idea great, if not, yah, we can just let the client request it again if they do.  I view it as more cosmetic as opposed to functional

**Comment by stdavis** [comment]
Great. I'll close this issue for now then.
