### ISSUE TITLE
initial data import & nightly update

### ISSUE THREAD

**Issue by stdavis** [agrc/ironing-board#112]
As a user I want AGRC to harvest the realtor data from EdcUtah SQL Server Database so I will have information on properties I am interested in.

**Comment by steveoh** [comment]
waiting on connection string

**Comment by stdavis** [comment]
From Arthur:
>You can access our full list of active properties here with a json feed:
http://utahsuresites.com/rest/properties-all

>If you want a slightly more human-readable output, you can see the same data here in tabular form:
http://utahsuresites.com/properties-all   (this link will go away once we’re production-ready)

>Something to keep in mind is that we have three Property Types:  Land, Existing Office Building, Existing Industrial Building.   The three property types do not utilize all of the exact same fields.  For example, only Land has "Geo-Technical Assessment Available" and "Phase I Environment Assessment Available”
