### ISSUE TITLE
handle old URL's with UTM coordinates

### ISSUE THREAD

**Issue by stdavis** [agrc/ironing-board#114]
There are older URL's floating around that use UTM coordinates to zoom the map to a non-default extent. (e.g. http://locate.utah.gov/#x=476742&y=4602207&scale=1155581) When the new app (web mercator) loads these URL's it does not reproject them which causes the map to be zoomed to a bad extent. I believe that we can fix this problem by detecting UTM coordinates and reprojecting them.

- [ ] it would be nice to fix this for agrc/starch as well.

**Comment by steveoh** [comment]
That's a great idea. The coords are different enough it shouldn't be hard to figure out. I said it was the wild web :cowboy_hat_face: and these things happen. But this is a much nicer solution.
