### ISSUE TITLE
add label for enterprise zone expiration date

### ISSUE THREAD

**Issue by BGranberg** [agrc/ironing-board#117]
![screen shot 2017-01-26 at 2 49 48 pm](https://cloud.githubusercontent.com/assets/1766038/22351770/ba928a1c-e3d6-11e6-934d-4c0bf96a1cf8.png)

At some finer scale, Kelleigh would like to see the expiration date for the enterprise zones

**Comment by steveoh** [comment]
So maybe the bottom 5 or 6 levels? And there is a field in the enterprise zones data called expiration date?

**Comment by BGranberg** [comment]
Not, sure about field, I suspect so...It's a question for Buell 

if possible, Kelleigh would like a start and end date

**Comment by stdavis** [comment]
Dates are not currently part of this dataset. Sent David an email about it.

**Comment by stdavis** [comment]
David says he doesn't know where to get the start dates but the end dates are in `EXPYR`.

**Comment by stdavis** [comment]
Kelleigh gave David the start dates. He's going to add the data to a new field in SGID and let me know when he's done.

**Comment by stdavis** [comment]
David added a new field called `VALID` which has the start and end years. Use this field to label.
