### ISSUE TITLE
Add a basemap/imagery credit

### ISSUE THREAD

**Issue by BGranberg** [agrc/ironing-board#122]
technically we should have a way to cite 'Google' for the licensed imagery delivered (now this is scale specific)...i recommend that we develop this for locate and then apply elsewhere. we might as well give SGID credit for other basemaps etc.

**Comment by stdavis** [comment]
stdavis [8:26 AM] 
Is there any way to set the attribution for a layer (WebTiledLayer) that only shows up in the Attribution widget only at certain scales? This is in 3.x.

yann [9:16 AM] 
Hi @stdavis this is not supported, but there is a way to make it happen by using the same mechanism as the attribution for the basemaps.
```var webTileLayer = new WebTileLayer(...);
webTileLayer.hasAttributionData = true;
webTileLayer.attributionDataUrl = "some url";
```
the attribution data url should point to a json file that looks like this: https://static.arcgis.com/attribution/World_Street_Map. That should work

stdavis [9:20 AM] 
Awesome. Exactly what I was looking for. Thanks, @yann!

yann [9:20 AM] 
Never tried it, so let me know ;-)

stdavis [9:21 AM] 
Does the score determine the ordering within the attribute widget?

[9:21]  
Understood. Will do.

yann [9:23 AM] 
Hmm I don't know let me check

[9:24]  
yes, the score determine the order. it's in between 0 and 100. The API defaults to 100 if not defined

**Comment by stdavis** [comment]
This is in test now. You should see attribution for all AGRC base maps and Google for levels 17 and below for Google. Also the SITLA layer is attributed.
