### ISSUE TITLE
Business Resource Center (BRC) Data

### ISSUE THREAD

**Issue by jpechmann** [agrc/ironing-board#92]
Add business resource center data to map. @BGranberg, where is the data we currently have?

**Comment by stdavis** [comment]
@jpechmann: Did anything ever happen with this?

**Comment by jpechmann** [comment]
@BGranberg Do you remember if we were going to collect new data or not?

**Comment by jpechmann** [comment]
James and I will work on mapping these: http://business.utah.gov/start/brc/

**Comment by jpechmann** [comment]
@stdavis data is in K:\sdavis\share\BBEcon.gdb. I'd treat these the same as the workforce services locations.
