### ISSUE TITLE
Workforce Services Data

### ISSUE THREAD

**Issue by jpechmann** [agrc/ironing-board#93]
Add locations of workforce services buildings. Kelleigh is working on collecting this data. If it falls through, this task might not happen.

**Comment by stdavis** [comment]
@jpechmann: Did anything ever happen with this?

**Comment by jpechmann** [comment]
@stdavis Good question! I will ask.

**Comment by jpechmann** [comment]
@stdavis the data is in: K:\sdavis\share\BBEcon.gdb\WorkforceServicesLocations.

**Comment by stdavis** [comment]
Sounds good.

**Comment by stdavis** [comment]
@jpechmann: That data isn't there anymore. I think that I may have deleted it. Sorry! Can you recopy it? Or tell me where I can get it?

**Comment by stdavis** [comment]
Also, I need icons for this and BRC data.

**Comment by jpechmann** [comment]
@stdavis Okay, I've put the file in the folder again. 

As for icons, @ZachBeck, do you have icons that would work or should we ask Aaron? We need red icons similar to the other icons on locate (the tear dropped shape) that represent Workforce Service Employment Center Locations and icons that represent Business Resource Center (http://business.utah.gov/start/brc/) locations.

**Comment by stdavis** [comment]
Actually I'll need both the marker for the map and the icon for the legend. Here are examples for national parks:

[Archive.zip](https://github.com/agrc/ironing-board/files/337759/Archive.zip)

**Comment by ZachBeck** [comment]
You'll have to get them from Aaron, he created all the others.
