### ISSUE TITLE
Federal Land Feature Service [5hrs]

### ISSUE THREAD

**Issue by jpechmann** [agrc/ironing-board#97]
Feature service to be used as basic map reference and indicator of recreation activities. 

Data Layers:
1. USFS Boundaries
2. National Parks/Monuments Boundaries
3. Wilderness/Primitive Boundaries
4. Tribal Land Boundaries
5. Military Boundaries

**Comment by jpechmann** [comment]
Waiting on symbology.

**Comment by stdavis** [comment]
@jpechmann: Did you ever get the symbology? Are all of these layers in the SGID? If so, what are their names?

**Comment by jpechmann** [comment]
That's a really good question. @ZachBeck does this ring any bells? If not, that's okay, but you are the best place to start.

**Comment by mheagin** [comment]
All these layers are in SGID they are all part of LandOwnership, do query based on ADMIN.
DESIG field will have the name and a definition for each area.

**Comment by jpechmann** [comment]
Thanks @mheagin. I'm not sure why we were waiting on the symbology, I would think we could just use the classic land ownership layer file? Scott I'll play with it when I'm back in the office with ArcMap.

**Comment by jpechmann** [comment]
Okay @stdavis . The plan is to use the existing feature service for land ownership, no new symbology. 

Data Layers (only doing the first 3):
1. USFS Boundaries: AGENCY = 'USFS'
2. National Parks/Monuments Boundaries: AGENCY = 'NPS'
3. Wilderness/Primitive Boundaries: DESIG = 'Wilderness'

**Comment by stdavis** [comment]
@jpechmann Do you have icons that you want to use for the checkboxes?
![image](https://cloud.githubusercontent.com/assets/1326248/16393481/4178ea8c-3c6e-11e6-9a33-e41b5f6c455f.png)

**Comment by mheagin** [comment]
You might want to check with Zach, I think he has NP service symbols or
something similar that may work for you.

Mike

On Mon, Jun 27, 2016 at 1:51 PM, Scott Davis <notifications@github.com>
wrote:

> @jpechmann <https://github.com/jpechmann> Do you have icons that you want
> to use for the checkboxes?
> [image: image]
> <https://cloud.githubusercontent.com/assets/1326248/16393481/4178ea8c-3c6e-11e6-9a33-e41b5f6c455f.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/agrc/ironing-board/issues/97#issuecomment-228855383>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKLtm23smprkUg9AyUbtDaOz-SflpEWsks5qQCnGgaJpZM4HGDNY>
> .
>



-- 
Mike Heagin
AGRC
gis.utah.gov
801-537-9296
